apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ./kompose convert -f docker-compose.yml
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: db
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: db
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: ./kompose convert -f docker-compose.yml
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: db
    spec:
      containers:
        - env:
            - name: BACKEND_CORS_ORIGINS
              valueFrom:
                configMapKeyRef:
                  key: BACKEND_CORS_ORIGINS
                  name: env
            - name: DOCKER_IMAGE_BACKEND
              valueFrom:
                configMapKeyRef:
                  key: DOCKER_IMAGE_BACKEND
                  name: env
            - name: DOCKER_IMAGE_FRONTEND
              valueFrom:
                configMapKeyRef:
                  key: DOCKER_IMAGE_FRONTEND
                  name: env
            - name: DOMAIN
              valueFrom:
                configMapKeyRef:
                  key: DOMAIN
                  name: env
            - name: EMAILS_FROM_EMAIL
              valueFrom:
                configMapKeyRef:
                  key: EMAILS_FROM_EMAIL
                  name: env
            - name: ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  key: ENVIRONMENT
                  name: env
            - name: FIRST_SUPERUSER
              valueFrom:
                configMapKeyRef:
                  key: FIRST_SUPERUSER
                  name: env
            - name: FIRST_SUPERUSER_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: FIRST_SUPERUSER_PASSWORD
                  name: env
            - name: FRONTEND_HOST
              valueFrom:
                configMapKeyRef:
                  key: FRONTEND_HOST
                  name: env
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_DB
                  name: env
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_PASSWORD
                  name: env
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_PORT
                  name: env
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_USER
                  name: env
            - name: PROJECT_NAME
              valueFrom:
                configMapKeyRef:
                  key: PROJECT_NAME
                  name: env
            - name: SECRET_KEY
              valueFrom:
                configMapKeyRef:
                  key: SECRET_KEY
                  name: env
            - name: SENTRY_DSN
              valueFrom:
                configMapKeyRef:
                  key: SENTRY_DSN
                  name: env
            - name: SMTP_HOST
              valueFrom:
                configMapKeyRef:
                  key: SMTP_HOST
                  name: env
            - name: SMTP_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: SMTP_PASSWORD
                  name: env
            - name: SMTP_USER
              valueFrom:
                configMapKeyRef:
                  key: SMTP_USER
                  name: env
            - name: STACK_NAME
              valueFrom:
                configMapKeyRef:
                  key: STACK_NAME
                  name: env
            - name: TAG
              valueFrom:
                configMapKeyRef:
                  key: TAG
                  name: env
          image: postgres:17
          livenessProbe:
            exec:
              command:
                - pg_isready -U postgres -d app
            failureThreshold: 5
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 10
          name: db
          volumeMounts:
            - mountPath: /var/lib/postgresql/data/pgdata
              name: app-db-data
      restartPolicy: Always
      volumes:
        - name: app-db-data
          persistentVolumeClaim:
            claimName: app-db-data
