apiVersion: batch/v1
kind: Job
metadata:
  name: prestart
  labels:
    app: prestart
spec:
  template:
    metadata:
      labels:
        app: prestart
    spec:
      containers:
        - args:
            - bash
            - scripts/prestart.sh
          env:
            - name: BACKEND_CORS_ORIGINS
              valueFrom:
                configMapKeyRef:
                  key: BACKEND_CORS_ORIGINS
                  name: env
            - name: DOCKER_IMAGE_BACKEND
              valueFrom:
                configMapKeyRef:
                  key: DOCKER_IMAGE_BACKEND
                  name: env
            - name: DOCKER_IMAGE_FRONTEND
              valueFrom:
                configMapKeyRef:
                  key: DOCKER_IMAGE_FRONTEND
                  name: env
            - name: DOMAIN
              valueFrom:
                configMapKeyRef:
                  key: DOMAIN
                  name: env
            - name: EMAILS_FROM_EMAIL
              valueFrom:
                configMapKeyRef:
                  key: EMAILS_FROM_EMAIL
                  name: env
            - name: ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  key: ENVIRONMENT
                  name: env
            - name: FIRST_SUPERUSER
              valueFrom:
                configMapKeyRef:
                  key: FIRST_SUPERUSER
                  name: env
            - name: FIRST_SUPERUSER_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: FIRST_SUPERUSER_PASSWORD
                  name: env
            - name: FRONTEND_HOST
              valueFrom:
                configMapKeyRef:
                  key: FRONTEND_HOST
                  name: env
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_DB
                  name: env
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_PASSWORD
                  name: env
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_PORT
                  name: env
            - name: POSTGRES_SERVER
              value: db
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_USER
                  name: env
            - name: PROJECT_NAME
              valueFrom:
                configMapKeyRef:
                  key: PROJECT_NAME
                  name: env
            - name: SECRET_KEY
              valueFrom:
                configMapKeyRef:
                  key: SECRET_KEY
                  name: env
            - name: SENTRY_DSN
              valueFrom:
                configMapKeyRef:
                  key: SENTRY_DSN
                  name: env
            - name: SMTP_HOST
              valueFrom:
                configMapKeyRef:
                  key: SMTP_HOST
                  name: env
            - name: SMTP_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: SMTP_PASSWORD
                  name: env
            - name: SMTP_USER
              valueFrom:
                configMapKeyRef:
                  key: SMTP_USER
                  name: env
            - name: STACK_NAME
              valueFrom:
                configMapKeyRef:
                  key: STACK_NAME
                  name: env
            - name: TAG
              valueFrom:
                configMapKeyRef:
                  key: TAG
                  name: env
          image: fastapi-backend:latest
          name: prestart
      restartPolicy: OnFailure